tasks:
  - name: Install
    init: npm install
    command: npm run serve

ports:
  - port: 9000
    onOpen: open-preview

vscode:
  extensions:
    "dbaeumer.vscode-eslint",
    "EditorConfig.EditorConfig",
    "stylelint.vscode-stylelint",
    "esbenp.prettier-vscode",
    "usernamehw.errorlens",
    "mkaufman.HTMLHint",
    "deque-systems.vscode-axe-linter"


